### ISSUE TITLE
Must define RAZZLE_AUTH0_* or Error is thrown

### ISSUE THREAD

**Issue by jboxman** [aptotude/circle-build-health#9]
After running `yarn start` without defining any AUTH0 variables in `.env`:

```
Error: You must provide the domain configuration value to use passport-auth0.
    at /Users/jasonb/Self/projects/circle-build-health/node_modules/passport-auth0/lib/index.js:36:13
    at Array.forEach (<anonymous>)
    at new Strategy (/Users/jasonb/Self/projects/circle-build-health/node_modules/passport-auth0/lib/index.js:34:20)
    at Object../src/serverAuth.js (/Users/jasonb/Self/projects/circle-build-health/build/server.js:2289:16)    at __webpack_require__ (/Users/jasonb/Self/projects/circle-build-health/build/server.js:630:30)
    at fn (/Users/jasonb/Self/projects/circle-build-health/build/server.js:48:20)
    at Object../src/server.js (/Users/jasonb/Self/projects/circle-build-health/build/server.js:2017:71)
    at __webpack_require__ (/Users/jasonb/Self/projects/circle-build-health/build/server.js:630:30)
    at fn (/Users/jasonb/Self/projects/circle-build-health/build/server.js:48:20)
    at Object../src/index.js (/Users/jasonb/Self/projects/circle-build-health/build/server.js:1941:66)
```

I thought setting `RAZZLE_USE_AUTH0=false` would negate the need to define the other variables.

**Comment by wbeard** [comment]
Nice find! Yeah I'm trying to wrap my head around this as well. I think the code would just have to, at build time, not run/build that branch of code based off the `RAZZLE_USER_AUTH0` env variable. Any thoughts on this?

**Comment by wbeard** [comment]
@jboxman I believe this is fixed now. Can you confirm?

**Comment by wbeard** [comment]
Closing for now since it appears to be fixed
